### ISSUE TITLE
Валидация поля ввода VIN-кода

### ISSUE THREAD

**Issue by avtopro** [ByHorix/vin-decoder#6]
При валидации данных в случае с VIN-кодом лучше применить whitelist-подход (allow list), когда мы перечисляем разрешённые символы, вместо blacklist-подхода (block list), когда мы пытаемся перечислить все символы, которых не должно быть в поле — это практически невозможно.

То есть, мы знаем что VIN состоит из латинских букв и цифр (на самом деле допускаются даже не все буквы и цифры), а все остальные символы запрещены: это явный allow list. См. [Allow list vs block list](https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html#allow-list-vs-block-list).

Сейчас форма принимает даже такие значения: "ÀBÇĎĒĽÑŐŖŦŮŸ🤪123", то есть валидация пропускает много лишнего.

https://github.com/ByHorix/vin-decoder/blob/7f463979fabafe2b5a27b8e7535fe2b7ed9d3391/src/utils/isValid.js#L1-L7

**Comment by ByHorix** [comment]
Такой подход действительно предотвращает много возможных ошибочных запросов.
