### ISSUE TITLE
Настройка роутинга на GitHub Pages

### ISSUE THREAD

**Issue by avtopro** [ByHorix/vin-decoder#7]
Не является большой проблемой для тестового задания, но желательно чтобы после перезагрузки страницы приложение оставалось в прежнем состоянии (то есть, хотя бы на той же странице/адресе) и работало корректно. Сейчас после перезагрузки страницы мы получаем 404 как из-за редиректа `<Navigate replace to="/" />`, так и особенностей GitHub Pages.

Варианты решения описаны в документации [Create React App](https://create-react-app.dev/docs/deployment/#notes-on-client-side-routing), где предлагается два варианта: либо использование HashRouter, либо настройка редиректа для "внутренних" путей на GitHub Pages, плюс прописывание начального адреса "/vin-decoder" в baseName роутера. Полезно разобраться.

https://github.com/ByHorix/vin-decoder/blob/7f463979fabafe2b5a27b8e7535fe2b7ed9d3391/src/App.jsx#L14-L19

**Comment by ByHorix** [comment]
Удалось разобраться в этом вопросе. Я предполагал, что что-то было сделано не правильно при создании репозитория и его названии. При чём, и в package.json и в настройках репозитория указана homepage: "https://byhorix.github.io/vin-decoder/", но при первом же входе на сайт гит-хаб обрезал часть ссылки и оставлял только "https://byhorix.github.io". Но применение HashRouter решило проблему.
